name: Greeting on variable day

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  Test_Message: test_log_message

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: 'Log test message'
        run: echo "$Test_Message!"
